/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CfprngRand */

#ifndef _Included_CfprngRand
#define _Included_CfprngRand
#ifdef __cplusplus
extern "C" {
#endif
#undef CfprngRand_CFPRNG_SUCCESS
#define CfprngRand_CFPRNG_SUCCESS 0L
#undef CfprngRand_CFPRNG_ERR
#define CfprngRand_CFPRNG_ERR 1L
#undef CfprngRand_CFPRNG_MAX_RAND_BYTES
#define CfprngRand_CFPRNG_MAX_RAND_BYTES 1024L
/*
 * Class:     CfprngRand
 * Method:    cfprng_nist_rand
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_CfprngRand_cfprng_1nist_1rand
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     CfprngRand
 * Method:    cfprng_fips_tests
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CfprngRand_cfprng_1fips_1tests
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
