/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CfRsaCertGen */

#ifndef _Included_CfRsaCertGen
#define _Included_CfRsaCertGen
#ifdef __cplusplus
extern "C" {
#endif
#undef CfRsaCertGen_CFRSA_SUCCESS
#define CfRsaCertGen_CFRSA_SUCCESS 1L
#undef CfRsaCertGen_CFRSA_ERR
#define CfRsaCertGen_CFRSA_ERR 0L
#undef CfRsaCertGen_CFRSA_PEMBUF_SZ
#define CfRsaCertGen_CFRSA_PEMBUF_SZ 10000L
/*
 * Class:     CfRsaCertGen
 * Method:    cfrsa_certgen
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_CfRsaCertGen_cfrsa_1certgen
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
